server:
  port: 8085
spring:
  application:
    name: zuul-gateway
ribbon:
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 130000
#eureka:
#  instance:
#    hostname: localhost
#    port: 8761
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#    instance:
#      preferIpAddress: true


zuul:
  #  sensitiveHeaders: Cookie,Set-Cookie
  ribbon:
    eager-load:
      enabled: true
  routes:
    nooble-security:
      sensitiveHeaders:
      path: /oauth/**
      stripPrefix: false
      serviceId: user-authentication
    morningservice:
      sensitiveHeaders:
      path: /users/**
      stripPrefix: false
      serviceId: user-service
    eveningservice:
      sensitiveHeaders:
      path: /user/**
      stripPrefix: false
      serviceId: user-data
   